### PR TITLE
Adjust the form on small device

### PR DESCRIPTION
**Pull request by mark86092**
image

Try to solve #101 

Left side: before, Right side: after

### CODE REVIEW

**Comment by qcl** [comment]
👍

**Comment by barry800414** [comment]
default

這邊看會長這樣QQ，實際平均工時會跑掉
昨天就是調這個調很久調不好...

**Comment by mark86092** [comment]
image

Thanks @barry800414 showing the bug

**Comment by qcl** [comment]
LGTM

**Pull request merged**
