### PR TITLE
Emoji fix

### LINKED ISSUE #172: 表格區(3) 表情符號無法正常顯示
default

環境: windows 7 + chrome

### PR DESCRIPTION
**Pull request by mark86092**
Fix #172 
- Replace the character (win can not render it QQ)
- Add License (http://emojione.com/licensing/)
- Tweak style

Notice, I would like to keep two of `.emoji` class, for future usage.

### CODE REVIEW

**Comment by mark86092** [comment]
image

**Comment by barry800414** [comment]
I have reviewed it. 
scream怎麼那麼好笑XD

**Comment by mark86092** [comment]
:stuck_out_tongue_winking_eye:

**Comment by qcl** [comment]
I'd done my review, so sad about win is not able to show emoji characters, but those svgs are so cute :p

**Pull request merged**
