### PR TITLE
Let the query autoload on page load

### LINKED ISSUE #176: The query won't autoload
See
https://worktime.goodjob.life/show.html?job_title=%E8%A1%8C%E9%8A%B7%E4%BC%81%E5%8A%83%E4%BA%BA%E5%93%A1

### PR DESCRIPTION
**Pull request by mark86092**
Fix #176 

Please try this PR by your local

http://localhost:8000/show.html?job_title=行銷企劃人員

### CODE REVIEW

**Comment by barry800414** [comment]
It cannot work

**Comment by mark86092** [comment]
Can you describe more detail how it can not work?

**Comment by barry800414** [comment]
I copy the link and paste it to browser, however, there is no search-result-table shown 
I am also trying to understand why.

**Comment by mark86092** [comment]
Are you in `fix-url-loading` branch?

**Comment by barry800414** [comment]
有資料，我錯了..
剛眼殘 
對我在那個branch

**Comment by barry800414** [comment]
那兩個table放在一起其實不容易區分
之後要可以improve

**Comment by mark86092** [comment]
How about open a issue for future fix?

**Comment by barry800414** [comment]
我想應該沒問題了
我也開issue了

**Comment by qcl** [comment]
So this wont' fix now?

**Comment by qcl** [comment]
Oh, this PR fix that, XD

**Comment by mark86092** [comment]
Haha, change title

**Pull request merged**
