### PR TITLE
Remove contact us from navigation bar

### LINKED ISSUE #130: Navbar 在平板螢幕上太長，會分兩行
default

### PR DESCRIPTION
**Pull request by qcl**
To fix #130

### CODE REVIEW

**Comment by mark86092** [comment]
about us  的 contact 其實是連到下方section. 

 該移除嗎？

**Comment by barry800414** [comment]
about_us.html的不要移掉好了!

**Comment by qcl** [comment]
應該三個都拿掉了？

**Comment by qcl** [comment]
那我把它補回去

**Comment by qcl** [comment]
I'd added it back, please review this PR again, thanks.

**Comment by barry800414** [comment]
I have reviewed it .

**Comment by mark86092** [comment]
I just reviewed it. Oops, please wait for me XD

**Comment by barry800414** [comment]
sorry!! 其實我不太會抓多少人review可以merge

**Comment by qcl** [comment]
@barry800414 就看大家怎麼溝通囉，其實很不一定XD

**Comment by mark86092** [comment]
@barry800414 因為正好這個也有參與了，所以等個我吧:P

**Comment by barry800414** [comment]
ok!

**Pull request merged**
