### PR TITLE
Use bower

### PR DESCRIPTION
**Pull request by mark86092**
- jquery-ui
- vue-resource
- vue
- director
- bootstrap

all goes to bower managed

### CODE REVIEW

**Comment by barry800414** [comment]
不太會bower，不過我想應該沒問題

**Comment by mark86092** [comment]
You can review commit `102946b`, it is nothing but change the path.

I think I have fixed all the path, but more checking is needed

**Comment by barry800414** [comment]
https://github.com/goodjoblife/WorkTimeSurvey/blob/102946b396bde0e93521a6a1057ccf55fdc16b69/about_us.html#L22

是不是這行已經不需要，L144已經有include? 
好像每個page都有這行

**Comment by mark86092** [comment]
#239 是先只針對 js 去處理，css 沒有變

**Comment by barry800414** [comment]
但是jquery UI是連css一起用bower管理了?

**Comment by mark86092** [comment]
Updated: bootstrap css goes to bower component

**Comment by mark86092** [comment]
The page will be rewrite, close it

**Pull request closed without merging**
